name: github-app-docker-push

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Generate GitHub App token
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build image
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg GITHUB_TOKEN=${{ steps.app-token.outputs.token }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/my-test-image:latest .

      # Push image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-test-image:latest